export const GAMES = {
    ADD_SEARCH_LIST: 'ADD_SEARCH_LIST',
    ADD_TO_COLLECTION: 'ADD_TO_COLLECTION',
    ADD_DETAILS: 'ADD_DETAILS',
    GET_COLLECTION: 'GET_COLLECTION',
    DELETE_FROM_COLLECTION: 'DELETE_FROM_COLLECTION',
}