export const GAMES = {
    ADD_SEARCH_LIST: 'ADD_SEARCH_LIST',
    ADD_TO_COLLECTION: 'ADD_TO_COLLECTION',
    ADD_DETAILS: 'ADD_DETAILS',
    GET_DETAILS: 'GET_DETAILS',
    GET_COLLECTION: 'GET_COLLECTION',
    DELETE_FROM_COLLECTION: 'DELETE_FROM_COLLECTION',
    UPDATE_PLAYED_TIME: 'UPDATE_PLAYED_TIME',
}

export const SEARCH_TYPE = {
    GAMES: 'GAMES',
    FILMS: 'FILMS',
}